### ISSUE TITLE
Win release crashes due to unhandled exception

### ISSUE THREAD

**Issue by CJRipa** [benreid24/Stellaru#142]
First time I try stellaru, I just downloaded the new win release and when I try to start it crashes instantly due to an exception.

I leave the information of trace that I can obtain:

`daphne\server.py:11: UserWarning: Something has already installed a non-asyncio Twisted reactor. Attempting to uninstall it; you can fix this warning by importing daphne.server early in your codebase or finding the package that imports Twisted and importing it later on.
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "main.py", line 47, in main
  File "django\core\management\__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "django\core\management\commands\makemigrations.py", line 88, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "django\db\migrations\loader.py", line 53, in __init__
    self.build_graph()
  File "django\db\migrations\loader.py", line 214, in build_graph
    self.load_disk()
  File "django\db\migrations\loader.py", line 108, in load_disk
    migration_names = {
  File "django\db\migrations\loader.py", line 108, in <setcomp>
    migration_names = {
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py", line 71, in _pyi_pkgutil_iter_modules
TypeError: startswith first arg must be str or a tuple of str, not PureWindowsPath
[10008] Failed to execute script 'main' due to unhandled exception!`

I don't know if I'm doing something wrong or if it's my computer. 

Thank you for your help.

**Comment by benreid24** [comment]
Hey there, thanks for trying it out! This is due to the package that I use to create the executables being updated to a non-working version. I am currently working on a fix or finding a better package. Will update you once I have a working release.

**Comment by benreid24** [comment]
Here is a new release that works for me: https://github.com/benreid24/Stellaru/releases/tag/v3.0.6

Please let me know if it works for you!
